
trigger:
  branches:
    include:
    - pizzafactory
  tags:
    include:
    - v*

jobs:
- job: xtext_vscode_extension
  steps:

  - script: ./gradlew assemble
    workingDirectory: xtext-language-server
    displayName: Building the language server.

  - script: |
      npm install
      npx vsce package
    workingDirectory: xtext-vscode-extension
    displayName: Building and packaging the VSIX package.
 
  - task: GitHubRelease@0
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    inputs:
      gitHubConnection: PizzaFactory-PersonalAccessToken
      repositoryName: PizzaFactory/xtext-ide-extensions
      assets: xtext-vscode-extension/xtext-lang-*.vsix 
